# Generated by Django 5.1.2 on 2024-11-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='your_name',
            new_name='name',
        ),
    ]
